/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateCollection = /* GraphQL */ `
  subscription OnCreateCollection {
    onCreateCollection {
      belongs_to
      bibliographic_citation
      circa
      collection_category
      collectionmap_id
      create_date
      creator
      custom_key
      description
      display_date
      end_date
      heirarchy_path
      id
      identifier
      language
      location
      modified_date
      ownerinfo
      parent_collection
      provenance
      related_url
      rights_holder
      rights_statement
      source
      start_date
      subject
      thumbnail_path
      title
      visibility
      collectionmap {
        collection_id
        create_date
        id
        map_object
        modified_date
        collection {
          belongs_to
          bibliographic_citation
          circa
          collection_category
          collectionmap_id
          create_date
          creator
          custom_key
          description
          display_date
          end_date
          heirarchy_path
          id
          identifier
          language
          location
          modified_date
          ownerinfo
          parent_collection
          provenance
          related_url
          rights_holder
          rights_statement
          source
          start_date
          subject
          thumbnail_path
          title
          visibility
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
      archives {
        items {
          belongs_to
          bibliographic_citation
          circa
          contributor
          create_date
          creator
          custom_key
          description
          display_date
          end_date
          explicit
          extent
          format
          heirarchy_path
          id
          identifier
          item_category
          language
          location
          manifest_url
          medium
          modified_date
          parent_collection
          provenance
          reference
          related_url
          repository
          resource_type
          rights_holder
          rights_statement
          source
          start_date
          subject
          tags
          thumbnail_path
          title
          visibility
          createdAt
          updatedAt
        }
        nextToken
      }
    }
  }
`;
export const onUpdateCollection = /* GraphQL */ `
  subscription OnUpdateCollection {
    onUpdateCollection {
      belongs_to
      bibliographic_citation
      circa
      collection_category
      collectionmap_id
      create_date
      creator
      custom_key
      description
      display_date
      end_date
      heirarchy_path
      id
      identifier
      language
      location
      modified_date
      ownerinfo
      parent_collection
      provenance
      related_url
      rights_holder
      rights_statement
      source
      start_date
      subject
      thumbnail_path
      title
      visibility
      collectionmap {
        collection_id
        create_date
        id
        map_object
        modified_date
        collection {
          belongs_to
          bibliographic_citation
          circa
          collection_category
          collectionmap_id
          create_date
          creator
          custom_key
          description
          display_date
          end_date
          heirarchy_path
          id
          identifier
          language
          location
          modified_date
          ownerinfo
          parent_collection
          provenance
          related_url
          rights_holder
          rights_statement
          source
          start_date
          subject
          thumbnail_path
          title
          visibility
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
      archives {
        items {
          belongs_to
          bibliographic_citation
          circa
          contributor
          create_date
          creator
          custom_key
          description
          display_date
          end_date
          explicit
          extent
          format
          heirarchy_path
          id
          identifier
          item_category
          language
          location
          manifest_url
          medium
          modified_date
          parent_collection
          provenance
          reference
          related_url
          repository
          resource_type
          rights_holder
          rights_statement
          source
          start_date
          subject
          tags
          thumbnail_path
          title
          visibility
          createdAt
          updatedAt
        }
        nextToken
      }
    }
  }
`;
export const onDeleteCollection = /* GraphQL */ `
  subscription OnDeleteCollection {
    onDeleteCollection {
      belongs_to
      bibliographic_citation
      circa
      collection_category
      collectionmap_id
      create_date
      creator
      custom_key
      description
      display_date
      end_date
      heirarchy_path
      id
      identifier
      language
      location
      modified_date
      ownerinfo
      parent_collection
      provenance
      related_url
      rights_holder
      rights_statement
      source
      start_date
      subject
      thumbnail_path
      title
      visibility
      collectionmap {
        collection_id
        create_date
        id
        map_object
        modified_date
        collection {
          belongs_to
          bibliographic_citation
          circa
          collection_category
          collectionmap_id
          create_date
          creator
          custom_key
          description
          display_date
          end_date
          heirarchy_path
          id
          identifier
          language
          location
          modified_date
          ownerinfo
          parent_collection
          provenance
          related_url
          rights_holder
          rights_statement
          source
          start_date
          subject
          thumbnail_path
          title
          visibility
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
      archives {
        items {
          belongs_to
          bibliographic_citation
          circa
          contributor
          create_date
          creator
          custom_key
          description
          display_date
          end_date
          explicit
          extent
          format
          heirarchy_path
          id
          identifier
          item_category
          language
          location
          manifest_url
          medium
          modified_date
          parent_collection
          provenance
          reference
          related_url
          repository
          resource_type
          rights_holder
          rights_statement
          source
          start_date
          subject
          tags
          thumbnail_path
          title
          visibility
          createdAt
          updatedAt
        }
        nextToken
      }
    }
  }
`;
export const onCreateCollectionmap = /* GraphQL */ `
  subscription OnCreateCollectionmap {
    onCreateCollectionmap {
      collection_id
      create_date
      id
      map_object
      modified_date
      collection {
        belongs_to
        bibliographic_citation
        circa
        collection_category
        collectionmap_id
        create_date
        creator
        custom_key
        description
        display_date
        end_date
        heirarchy_path
        id
        identifier
        language
        location
        modified_date
        ownerinfo
        parent_collection
        provenance
        related_url
        rights_holder
        rights_statement
        source
        start_date
        subject
        thumbnail_path
        title
        visibility
        collectionmap {
          collection_id
          create_date
          id
          map_object
          modified_date
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
        archives {
          nextToken
        }
      }
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateCollectionmap = /* GraphQL */ `
  subscription OnUpdateCollectionmap {
    onUpdateCollectionmap {
      collection_id
      create_date
      id
      map_object
      modified_date
      collection {
        belongs_to
        bibliographic_citation
        circa
        collection_category
        collectionmap_id
        create_date
        creator
        custom_key
        description
        display_date
        end_date
        heirarchy_path
        id
        identifier
        language
        location
        modified_date
        ownerinfo
        parent_collection
        provenance
        related_url
        rights_holder
        rights_statement
        source
        start_date
        subject
        thumbnail_path
        title
        visibility
        collectionmap {
          collection_id
          create_date
          id
          map_object
          modified_date
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
        archives {
          nextToken
        }
      }
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteCollectionmap = /* GraphQL */ `
  subscription OnDeleteCollectionmap {
    onDeleteCollectionmap {
      collection_id
      create_date
      id
      map_object
      modified_date
      collection {
        belongs_to
        bibliographic_citation
        circa
        collection_category
        collectionmap_id
        create_date
        creator
        custom_key
        description
        display_date
        end_date
        heirarchy_path
        id
        identifier
        language
        location
        modified_date
        ownerinfo
        parent_collection
        provenance
        related_url
        rights_holder
        rights_statement
        source
        start_date
        subject
        thumbnail_path
        title
        visibility
        collectionmap {
          collection_id
          create_date
          id
          map_object
          modified_date
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
        archives {
          nextToken
        }
      }
      createdAt
      updatedAt
    }
  }
`;
export const onCreateArchive = /* GraphQL */ `
  subscription OnCreateArchive {
    onCreateArchive {
      belongs_to
      bibliographic_citation
      circa
      contributor
      create_date
      creator
      custom_key
      description
      display_date
      end_date
      explicit
      extent
      format
      heirarchy_path
      id
      identifier
      item_category
      language
      location
      manifest_url
      medium
      modified_date
      parent_collection
      provenance
      reference
      related_url
      repository
      resource_type
      rights_holder
      rights_statement
      source
      start_date
      subject
      tags
      thumbnail_path
      title
      visibility
      collection {
        belongs_to
        bibliographic_citation
        circa
        collection_category
        collectionmap_id
        create_date
        creator
        custom_key
        description
        display_date
        end_date
        heirarchy_path
        id
        identifier
        language
        location
        modified_date
        ownerinfo
        parent_collection
        provenance
        related_url
        rights_holder
        rights_statement
        source
        start_date
        subject
        thumbnail_path
        title
        visibility
        collectionmap {
          collection_id
          create_date
          id
          map_object
          modified_date
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
        archives {
          nextToken
        }
      }
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateArchive = /* GraphQL */ `
  subscription OnUpdateArchive {
    onUpdateArchive {
      belongs_to
      bibliographic_citation
      circa
      contributor
      create_date
      creator
      custom_key
      description
      display_date
      end_date
      explicit
      extent
      format
      heirarchy_path
      id
      identifier
      item_category
      language
      location
      manifest_url
      medium
      modified_date
      parent_collection
      provenance
      reference
      related_url
      repository
      resource_type
      rights_holder
      rights_statement
      source
      start_date
      subject
      tags
      thumbnail_path
      title
      visibility
      collection {
        belongs_to
        bibliographic_citation
        circa
        collection_category
        collectionmap_id
        create_date
        creator
        custom_key
        description
        display_date
        end_date
        heirarchy_path
        id
        identifier
        language
        location
        modified_date
        ownerinfo
        parent_collection
        provenance
        related_url
        rights_holder
        rights_statement
        source
        start_date
        subject
        thumbnail_path
        title
        visibility
        collectionmap {
          collection_id
          create_date
          id
          map_object
          modified_date
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
        archives {
          nextToken
        }
      }
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteArchive = /* GraphQL */ `
  subscription OnDeleteArchive {
    onDeleteArchive {
      belongs_to
      bibliographic_citation
      circa
      contributor
      create_date
      creator
      custom_key
      description
      display_date
      end_date
      explicit
      extent
      format
      heirarchy_path
      id
      identifier
      item_category
      language
      location
      manifest_url
      medium
      modified_date
      parent_collection
      provenance
      reference
      related_url
      repository
      resource_type
      rights_holder
      rights_statement
      source
      start_date
      subject
      tags
      thumbnail_path
      title
      visibility
      collection {
        belongs_to
        bibliographic_citation
        circa
        collection_category
        collectionmap_id
        create_date
        creator
        custom_key
        description
        display_date
        end_date
        heirarchy_path
        id
        identifier
        language
        location
        modified_date
        ownerinfo
        parent_collection
        provenance
        related_url
        rights_holder
        rights_statement
        source
        start_date
        subject
        thumbnail_path
        title
        visibility
        collectionmap {
          collection_id
          create_date
          id
          map_object
          modified_date
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
        archives {
          nextToken
        }
      }
      createdAt
      updatedAt
    }
  }
`;
export const onCreateSite = /* GraphQL */ `
  subscription OnCreateSite {
    onCreateSite {
      analyticsID
      assetBasePath
      browseCollections
      contact
      displayedAttributes
      groups
      homePage
      id
      lang
      miradorOptions
      searchPage
      siteColor
      siteId
      siteName
      sitePages
      siteTitle
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateSite = /* GraphQL */ `
  subscription OnUpdateSite {
    onUpdateSite {
      analyticsID
      assetBasePath
      browseCollections
      contact
      displayedAttributes
      groups
      homePage
      id
      lang
      miradorOptions
      searchPage
      siteColor
      siteId
      siteName
      sitePages
      siteTitle
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteSite = /* GraphQL */ `
  subscription OnDeleteSite {
    onDeleteSite {
      analyticsID
      assetBasePath
      browseCollections
      contact
      displayedAttributes
      groups
      homePage
      id
      lang
      miradorOptions
      searchPage
      siteColor
      siteId
      siteName
      sitePages
      siteTitle
      createdAt
      updatedAt
    }
  }
`;
export const onCreateHistory = /* GraphQL */ `
  subscription OnCreateHistory {
    onCreateHistory {
      event
      groups
      id
      siteID
      userEmail
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateHistory = /* GraphQL */ `
  subscription OnUpdateHistory {
    onUpdateHistory {
      event
      groups
      id
      siteID
      userEmail
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteHistory = /* GraphQL */ `
  subscription OnDeleteHistory {
    onDeleteHistory {
      event
      groups
      id
      siteID
      userEmail
      createdAt
      updatedAt
    }
  }
`;
